# Generated by Django 4.2 on 2024-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
                ('duration', models.CharField(max_length=20)),
                ('age_limit', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('kino', 'Kino'), ('anime', 'Anime'), ('serial', 'Serial'), ('multfilm', 'Multfilm')], max_length=20)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
