# Generated by Django 4.2 on 2024-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
